spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        btc-in:
          destination: btcrates
          contentType: application/json
        btc-out:
          destination: btcrates
          contentType: application/json